### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by GalaxyHQ** [Snuggle/hypixel.py#10]
After I ran `pip install hypixel` and running code from the examples file, I got this error. I even checked to make sure it was in `site-packages`. It wasn't. I kept trying and I still got the following error. I need help.

> Traceback (most recent call last):
  File "C:/Users/notMyUsername/OneDrive/Documents/PythonStuff/Random/lol.py", line 1, in <module>
    import hypixel
ModuleNotFoundError: No module named 'hypixel'

**Comment by Snuggle** [comment]
Testing this on a Linux machine without it installed, I can't reproduce this.
```

~ 
➜ python3                     
Python 3.6.4 (default, Mar 13 2018, 04:02:38) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hypixel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'hypixel'
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> exit()

~ took 9s 
➜ sudo pip3 install hypixel     
Password: 
Collecting hypixel
  Downloading hypixel-0.7.6-py2.py3-none-any.whl
Collecting grequests (from hypixel)
  Downloading grequests-0.3.0.tar.gz
Collecting gevent (from grequests->hypixel)
  Downloading gevent-1.2.2-cp36-cp36m-manylinux1_x86_64.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 725kB/s 
Requirement already satisfied: requests in /usr/lib64/python3.6/site-packages (from grequests->hypixel)
Collecting greenlet>=0.4.10 (from gevent->grequests->hypixel)
  Downloading greenlet-0.4.13-cp36-cp36m-manylinux1_x86_64.whl (43kB)
    100% |████████████████████████████████| 51kB 6.9MB/s 
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib64/python3.6/site-packages (from requests->grequests->hypixel)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib64/python3.6/site-packages (from requests->grequests->hypixel)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/lib64/python3.6/site-packages (from requests->grequests->hypixel)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib64/python3.6/site-packages (from requests->grequests->hypixel)
Installing collected packages: greenlet, gevent, grequests, hypixel
  Running setup.py install for grequests ... done
Successfully installed gevent-1.2.2 greenlet-0.4.13 grequests-0.3.0 hypixel-0.7.6

~ took 7s 
➜ python3
Python 3.6.4 (default, Mar 13 2018, 04:02:38) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hypixel
>>> 
```

I feel like you might be running `./lol.py` with Python 2.7 or something similar. If you open the command prompt and do the following commands, could you please post the output? :smiley: 

`python --version`
`python3 --version`
`pip --version`
`pip3 --version`

**Comment by Snuggle** [comment]
I've also decided to test this in a fresh Windows 10 virtual machine, to make sure I didn't mess anything up for the Windows side of things. :yum:

I'll attach the YouTube URL here. It might help to follow along the steps - you might've installed Python 2 or something? Not sure. c:

**Here's a step-by-step on how to install Python 3.6 & hypixel.py on Windows:** https://www.youtube.com/watch?v=vmlXtVRQ0KU 
_(Sorry for it being a slow video, feel free to skip ahead.)_

Please make 100% sure you're using Python 3 to run the Python file, and not Python 2. It's possible to have both versions installed, which can get complicated.

As for looking in site-packages, the following things should be in there. Note that `hypixel.py` isn't inside of a folder:
![image](https://user-images.githubusercontent.com/26250962/38651511-89e73f56-3df9-11e8-87ca-ce39f62736c3.png)

If you have any more questions, or if you still can't figure things out, I'd be more than happy to help!

**Comment by GalaxyHQ** [comment]
I was able to make this work on two devices...Mac and Windows. Thanks for the help. Closing it now.
