### ISSUE TITLE
When will the example of minigame statistics be added?

### ISSUE THREAD

**Issue by urFate** [Snuggle/hypixel.py#13]

**Comment by Snuggle** [comment]
I haven't worked on this project for quite a while, but this is something you should access with JSON! Could you give an example of a statistic you'd like and I could try to show how to retrieve it? 😊

**Comment by urFate** [comment]
Easy-peasy. :D
https://pastebin.com/TSzgKbXE
Examples needed for new coders)

**Comment by urFate** [comment]
And pls change default player rank 'non' to 'DEFAULT'
And correct the display of the player level, because of the fact that there are too many digits)
http://prntscr.com/mor8e0

Do not throw this project, perhaps its big future) ☄

**Comment by Snuggle** [comment]
I can make these changes for you and include your example!

I'll clean your example up a little though.
`optionInput = input("Please select from list: {}\n> ".format(options))`

Could be better written as:

`optionInput = input(f"Please select from list: {options}\n> ")`

**Comment by urFate** [comment]
Good no problem, I will be very happy. It is very good that you help me.
