### ISSUE TITLE
hypixel.PlayerNotFoundException Not working!

### ISSUE THREAD

**Issue by urFate** [Snuggle/hypixel.py#14]
hypixel.PlayerNotFoundException Not working in all files, and even in the advanced example. :/

**Comment by Snuggle** [comment]
Hey! Could you please post any error message you receive? What do you mean by "not working"? 😊

**Comment by urFate** [comment]
Ok, let's take an advanced example.
If I enter a non-existent nickname, then the console does not display a message stating that "the player was not found", but this error.
http://prntscr.com/mor3sx

**Comment by urFate** [comment]
Oh sorry, i stupid kid :D

**Comment by Snuggle** [comment]
Yep! This is a custom exception that's telling you that the player is not found!

To catch this error, try something like:
```
try:
    doThings()
except PlayerNotFoundException:
    print("This player does not exist!")
```
