### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by urFate** [Snuggle/hypixel.py#15]
How to make it so that if a player has no karma, it would be written something like this:
Player Karma: 0
or Player Karma: 110
And did not separate the separate message that there is no karma?

**Comment by Snuggle** [comment]
```
def get_karma(player_object):
    try:
        karma = player_object.JSON['karma']
    except KeyError:
        karma = 0

print(f"Player has exactly: {get_karma(player)} karma!")
```
😛

**Comment by urFate** [comment]
In any case, if a player has or does not have a karma, the result is always 'none'. :-1:

**Comment by Snuggle** [comment]
How did you get along with the solution above? If you're still having issues, feel free to reopen an issue!
