### ISSUE TITLE
Check if a username exists

### ISSUE THREAD

**Issue by QuestwalkerKO** [Snuggle/hypixel.py#16]
Can you check if a username exists, and what their rank is?

_its for a discord bot_

**Comment by QuestwalkerKO** [comment]
oh nvm --> https://gitlab.com/Snuggle/hypixel.py/blob/master/.examples/simpleExample.py

**Comment by Snuggle** [comment]
Good luck and feel free to ask any more questions!
(Apologies for the slow reply, I was not home. 😋)
