### ISSUE TITLE
No module named hypixel

### ISSUE THREAD

**Issue by sp0nGe66** [Snuggle/hypixel.py#18]
I followed the installation process and still got this error.
`File "D:\Documents\Discord Bot\Addicts Discord Bot\bot.py", line 1, in <module>
    import hypixel
ModuleNotFoundError: No module named 'hypixel''`
I did "pip install hypixel"
and at the top of my code I have "import hypixel".

Thanks in advance

**Comment by Swuup** [comment]
> I followed the installation process and still got this error.
> `File "D:\Documents\Discord Bot\Addicts Discord Bot\bot.py", line 1, in <module> import hypixel ModuleNotFoundError: No module named 'hypixel''`
> I did "pip install hypixel"
> and at the top of my code I have "import hypixel".
> 
> Thanks in advance

Did you run ```pip install hypixel (windows)```

**Comment by Snuggle** [comment]
## Works alright for me! 🎉
Using MacOS, also have previously tested with Linux and Windows
<img width="1440" alt="Screen Shot 2020-09-29 at 7 30 59 PM" src="https://user-images.githubusercontent.com/26250962/94600946-9eece600-028a-11eb-8fe8-c736c613a020.png">
