### ISSUE TITLE
Support for Python 3.8

### ISSUE THREAD

**Issue by ghost** [Snuggle/hypixel.py#19]
Can't seem to install due to Python 3.8, is there a way for 3.8 support to be added?

**Comment by Snuggle** [comment]
I'll give it a look! I don't think there should be any major changes needed for a new Python release, it'll just be a matter of testing it and adding it to the supported releases!

**Comment by Swuup** [comment]
Python 3.8 works fine with this on Linux.

**Comment by Snuggle** [comment]
## Works alright for me on macOS too! 🎉
<img width="1440" alt="Screen Shot 2020-09-29 at 7 30 59 PM" src="https://user-images.githubusercontent.com/26250962/94600946-9eece600-028a-11eb-8fe8-c736c613a020.png">
