### ISSUE TITLE
Skyblock API Addition

### ISSUE THREAD

**Issue by Swuup** [Snuggle/hypixel.py#22]
# Idea

Add the API from Skyblock (https://api.hypixel.net/skyblock/)

# Why?

Makes life easier

**Comment by MySixSenses** [comment]
I will try to do this, but it may take a while

**Comment by MySixSenses** [comment]
It's PR #24 to add some basic auction and other classes.

**Comment by Snuggle** [comment]
Merged, thank you so much for this @MySixSenses!
