### ISSUE TITLE
Issue with hpyixel.py

### ISSUE THREAD

**Issue by oofsamy** [Snuggle/hypixel.py#31]
I have a discord.py bot, and inside the command I had this in here `player = hypixel.Player(name)` and it errors with this: `list index out of range` on it, name is valid and is `oofsamy`, hypixel is `import hypixel`

**Comment by oofsamy** [comment]
Oh my god i'm very stupid sorry for the issue, I forgot to set the api key

**Comment by Snuggle** [comment]
Glad you got it working! 🎉
